services:
  devops-backend-preprod:
    image: ${BACKEND_IMAGE}:${IMAGE_TAG}
    container_name: devops-backend-preprod
    ports:
      - "8003:8000"
    environment:
      - DEBUG=${PREPROD_DEBUG}
      - ALLOWED_HOSTS=${PREPROD_ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${PREPROD_CORS_ALLOWED_ORIGINS}
      - SECRET_KEY=${PREPROD_SECRET_KEY}
    volumes:
      - devops_backend_static_preprod:/app/staticfiles
    networks:
      - devops-preprod-network
    restart: unless-stopped

  devops-frontend-preprod:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}
    container_name: devops-frontend-preprod
    ports:
      - "5176:5173"
    environment:
      - VITE_API_URL=${PREPROD_VITE_API_URL}
    depends_on:
      - devops-backend-preprod
    networks:
      - devops-preprod-network
    restart: unless-stopped

volumes:
  devops_backend_static_preprod:
    name: devops_backend_static_preprod

networks:
  devops-preprod-network:
    name: devops-preprod-network
    driver: bridge