services:
  devops-backend-preprod:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runtime
    container_name: devops-backend-preprod
    ports:
      - "8003:8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=preprod.api.nextgensis.mooazsayyed.live,localhost,127.0.0.1,54.87.192.112
      - CORS_ALLOWED_ORIGINS=https://preprod.nextgensis.mooazsayyed.live,http://54.87.192.112
      - ENVIRONMENT=pre-production
      - SECRET_KEY=django-preprod-secret-key-abcde
    volumes:
      - devops_backend_static_preprod:/app/staticfiles
    networks:
      - devops-preprod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  devops-frontend-preprod:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runtime
    container_name: devops-frontend-preprod
    ports:
      - "5176:5173"
    environment:
      - VITE_API_URL=https://preprod.api.nextgensis.mooazsayyed.live
    depends_on:
      - devops-backend-preprod
    networks:
      - devops-preprod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

volumes:
  devops_backend_static_preprod:
    name: devops_backend_static_preprod

networks:
  devops-preprod-network:
    name: devops-preprod-network
    driver: bridge