services:
  devops-backend-prod:
    image: ${BACKEND_IMAGE}:${IMAGE_TAG}
    container_name: devops-backend-prod
    ports:
      - "8004:8000"
    environment:
      - DEBUG=${PROD_DEBUG}
      - ALLOWED_HOSTS=${PROD_ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${PROD_CORS_ALLOWED_ORIGINS}
      - SECRET_KEY=${PROD_SECRET_KEY}
    volumes:
      - devops_backend_static_prod:/app/staticfiles
    networks:
      - devops-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

  devops-frontend-prod:
    image: ${FRONTEND_IMAGE}:${IMAGE_TAG}
    container_name: devops-frontend-prod
    ports:
      - "5177:5173"
    environment:
      - VITE_API_URL=${PROD_VITE_API_URL}
    depends_on:
      - devops-backend-prod
    networks:
      - devops-prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: unless-stopped

volumes:
  devops_backend_static_prod:
    name: devops_backend_static_prod

networks:
  devops-prod-network:
    name: devops-prod-network
    driver: bridge